# -*- coding: utf-8 -*-
"""synent-task3-eda-beshoynashaat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QKQ71yDxxoIeZmir9UEIhVU3cwW2P3YA

# Exploratory Data Analysis: Netflix Dataset
In this section, we will explore the dataset to uncover trends and patterns using statistical methods and visualizations.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set plotting style
sns.set(style='whitegrid')

# Load the dataset (Update the path to your Netflix CSV file)
df = pd.read_csv('/content/netflix_titles.csv')
print('Libraries imported and plotting style set.')

"""## 1. Summary Statistics
We'll start by checking the dataset structure and basic descriptive statistics.
"""

# Check data info and missing values
print(df.info())

# Descriptive statistics for numerical columns
display(df.describe(include='all'))

"""## 2. Trend Identification
Let's visualize the distribution of content types (Movies vs. TV Shows) and the release years.
"""

# Content Type Distribution
plt.figure(figsize=(8, 5))
sns.countplot(x='type', data=df, palette='viridis')
plt.title('Distribution of Movies and TV Shows')
plt.show()

# Growth in content over the years
plt.figure(figsize=(12, 6))
sns.histplot(df['release_year'], bins=30, kde=True, color='red')
plt.title('Content Release Year Distribution')
plt.xlabel('Release Year')
plt.ylabel('Count')
plt.show()